
services:
  app:
    build: ./app
    working_dir: /usr/app
    command: npx nodemon -L index.js
    volumes:
      - ./app:/usr/app
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
